packages/shipjs-lib/package.json, packages/shipjs-lib/src/lib/git/getRepoURL.js, yarn.lock
It didn't get repo url correctly due to the bad usage of `hub browse -u`.
=> fix: fix getRepoUrl

CHANGELOG.md, lerna.json, package.json, packages/shipjs-cli/package.json, packages/shipjs-lib/package.json
- Version change: `v0.0.6` → `v0.0.7`
- Merge: `releases/v0.0.7` → `master`
- [Compare the changes between the versions](https://github.com/algolia/shipjs/compare/v0.0.6...releases/v0.0.7)
=> chore: release v0.0.7

packages/shipjs-cli/src/flow/prepare.js, packages/shipjs-cli/src/flow/release.js, packages/shipjs-cli/src/util/run.js
closes https://github.com/algolia/shipjs/issues/83
=> feat: add --dry-run option

packages/shipjs-lib/src/lib/config/defaultConfig.js
=> fix: fix publishing command in yarn

packages/shipjs-cli/src/flow/release.js
=> fix: push commits and tag after release

packages/shipjs-cli/src/flow/prepare.js, packages/shipjs-lib/src/lib/config/defaultConfig.js
=> chore: add option to disable changelog

packages/shipjs-cli/src/flow/prepare.js, packages/shipjs-cli/src/flow/release.js, packages/shipjs-lib/src/lib/config/__tests__/example/ship.config.js, packages/shipjs-lib/src/lib/config/__tests__/loadConfig.spec.js, packages/shipjs-lib/src/lib/config/defaultConfig.js
=> chore: remove baseBranches from config

CHANGELOG.md, lerna.json, package.json, packages/shipjs-cli/package.json, packages/shipjs-lib/package.json
- Version change: `v0.0.8` → `v0.1.0`
- Merge: `releases/v0.1.0` → `master`
- [Compare the changes between the versions](https://github.com/algolia/shipjs/compare/v0.0.8...releases/v0.1.0)
=> chore: release v0.1.0

CHANGELOG.md, lerna.json, package.json, packages/shipjs-lib/package.json, packages/shipjs/package.json
- Version change: `v0.1.0` → `v0.1.1`
- Merge: `releases/v0.1.1` → `master`
- [Compare the changes between the versions](https://github.com/algolia/shipjs/compare/v0.1.0...releases/v0.1.1)
=> chore: release v0.1.1

GUIDE.md
=> docs: update GUIDE.md

packages/shipjs/bin/shipjs
=> fix: exit with non-zero if failed

packages/shipjs-lib/src/lib/config/defaultConfig.js, packages/shipjs/src/flow/prepare.js
=> feat(reviwer): add config to assign reviewer when creating PR

CHANGELOG.md, lerna.json, package.json, packages/shipjs-lib/package.json, packages/shipjs/package.json, packages/shipjs/src/version.js
- Version change: `v0.1.1` → `v0.2.0`
- Merge: `releases/v0.2.0` → `master`
- [Compare the changes between the versions](https://github.com/algolia/shipjs/compare/v0.1.1...releases/v0.2.0)
=> chore: release v0.2.0

GUIDE.md, README.md
=> docs: update guide

.circleci/config.yml, GUIDE.md
=> docs: update guide about scheduled release

CHANGELOG.md, GUIDE.md, lerna.json, package.json, packages/shipjs-lib/package.json, packages/shipjs/package.json, packages/shipjs/src/version.js
- Version change: `v0.2.0` → `v0.3.0`
- Merge: `releases/v0.3.0` → `master`
- [Compare the changes between the versions](https://github.com/algolia/shipjs/compare/v0.2.0...releases/v0.3.0)
=> chore: release v0.3.0

CHANGELOG.md, lerna.json, package.json, packages/shipjs-lib/package.json, packages/shipjs/package.json, packages/shipjs/src/version.js
- Version change: `v0.3.0` → `v0.3.1`
- Merge: `releases/v0.3.1` → `master`
- [Compare the changes between the versions](https://github.com/algolia/shipjs/compare/v0.3.0...releases/v0.3.1)
=> chore: release v0.3.1

CHANGELOG.md, GUIDE.md, lerna.json, package.json, packages/shipjs-lib/package.json, packages/shipjs/package.json, packages/shipjs/src/version.js
- Version change: `v0.3.1` → `v0.3.2`
- Merge: `releases/v0.3.2` → `master`
- [Compare the changes between the versions](https://github.com/algolia/shipjs/compare/v0.3.1...releases/v0.3.2)
=> chore: release v0.3.2

CHANGELOG.md, lerna.json, package.json, packages/shipjs-lib/package.json, packages/shipjs/package.json, packages/shipjs/src/version.js
- Version change: `v0.3.2` → `v0.3.3`
- Merge: `releases/v0.3.3` → `master`
- [Compare the changes between the versions](https://github.com/algolia/shipjs/compare/v0.3.2...releases/v0.3.3)
=> chore: release v0.3.3

GUIDE.md
=> docs: update guide on GITHUB_TOKEN

README.md
Add documentation for creating GitHub release.
=> docs: add description for GitHub release

.all-contributorsrc, README.md
Thanks for your contribution 🎉  #381 cc @jeetiss
=> docs: add @jeetiss as a contributor

packages/shipjs/src/cli.js
=> fix(chore): warn appropriately on supplying invalid flags

.all-contributorsrc, README.md
=> docs: add @jamesgeorge007 as a contributor

packages/shipjs-lib/src/lib/config/defaultConfig.js, packages/shipjs/src/step/prepare/__tests__/commitChanges.spec.js, packages/shipjs/src/step/prepare/commitChanges.js
=> fix: pass `nextVersion` to `beforeCommitChanges`

packages/shipjs/src/helper/hubConfigured.js
=> fix: fix hubConfigured for GitHub Actions

.all-contributorsrc, README.md
=> chore: add @tyankatsu0105 as a contributor

packages/shipjs/src/step/setup/addDevDependencies.js
=> fix: pin dependency at shipjs setup

packages/shipjs/src/flow/prepare.js, packages/shipjs/src/step/prepare/fetchTags.js
=> fix(prepare): fetch tags before figuring out next version

packages/shipjs-lib/src/lib/util/__tests__/getNextVersion.spec.js, packages/shipjs-lib/src/lib/util/getNextVersion.js, packages/shipjs/src/step/prepare/getNextVersion.js
=> chore: pass commitRange to getNextVersion

packages/shipjs/src/flow/prepare.js, packages/shipjs/src/helper/__tests__/validateBeforePrepare.spec.js, packages/shipjs/src/helper/validateBeforePrepare.js, packages/shipjs/src/step/prepare/__tests__/validate.spec.js, packages/shipjs/src/step/prepare/getCommitRange.js, packages/shipjs/src/step/prepare/getNextVersion.js, packages/shipjs/src/step/prepare/validate.js
=> fix(prepare): ask commit range when tag is missing

packages/shipjs/src/step/setup/addShipConfig.js
=> revert: "fix(setup): add eslint disable comment to ship.config.js"

packages/shipjs-lib/src/lib/config/defaultConfig.js, packages/shipjs/src/step/prepare/__tests__/updateVersion.spec.js, packages/shipjs/src/step/prepare/__tests__/updateVersionMonorepo.spec.js, packages/shipjs/src/step/prepare/commitChanges.js, packages/shipjs/src/step/prepare/updateVersion.js, packages/shipjs/src/step/prepare/updateVersionMonorepo.js
=> fix(prepare): make `versionUpdated` and `beforeCommitChanges` undefined by default

packages/shipjs/src/flow/prepare.js
=> fix(prepare): add missing pr url to slack message

README.md, website/.vuepress/config.js, website/guide/community.md
=> docs: add chat link

package.json, packages/shipjs/bin/shipjs
- Remove description
- I think description in root is unnecessary with Lerna
- See: https://github.com/vuejs/vue-cli/blob/dev/package.json https://github.com/babel/babel/blob/master/package.json
- Remove main
- It seems like unused.
=> chore: remove unnecessary code in root's package.json

.all-contributorsrc, README.md
=> docs: add @haroenv as a contributor

packages/shipjs/src/flow/prepare.js, packages/shipjs/src/step/prepare/__tests__/printHelp.spec.js, packages/shipjs/src/step/prepare/getRevisionRange.js, packages/shipjs/src/step/prepare/printHelp.js
=> feat(prepare): add --commit-from option

packages/shipjs/bin/shipjs
=> feat: add environment variable `SHIPJS=true`

.all-contributorsrc, README.md
=> docs: add @heavenshell as a contributor

packages/shipjs-lib/src/lib/config/defaultConfig.js, packages/shipjs/src/step/setup/addShipConfig.js, website/reference/all-config.md
=> fix: empty testCommandBeforeRelease by default

packages/shipjs/src/step/prepare/updateChangelog.js
=> fix: create CHANGELOG if missing

packages/shipjs/src/flow/setup.js
=> chore: show guide URL at the end of setup command

packages/shipjs/src/helper/__tests__/getPackageDirName.spec.js, packages/shipjs/src/helper/getPackageDirName.js, packages/shipjs/src/helper/index.js, packages/shipjs/src/step/prepare/createPullRequest.js
=> chore: refine publish commands on PR

packages/shipjs/src/step/setup/askQuestions.js
=> fix(setup): fix wrong config(packagesToBump, packagesToPublish) for monorepo

packages/shipjs/src/step/setup/addShipConfig.js
=> fix(setup): do not write ship.config.js if not necessary

packages/shipjs/src/step/setup/CI/addGitHubActions.js
Update GHA:
autogenerated commits are made with github-actions[bot] signature.
Like in [changesets](https://github.com/changesets/action/blob/master/index.ts#L43)
=> fix: use github-actions[bot] name and email for generated pull requests

packages/shipjs/src/step/setup/CI/addGitHubActions.js
=> fix(actions): fix ejs syntax

packages/shipjs/src/step/release/__tests__/gitPush.spec.js, packages/shipjs/src/step/release/gitPush.js
=> fix(release): push to correct branch in toReleaseBranch strategy

.circleci/config.yml, package.json, packages/shipjs-lib/tests/bootstrap.sh, packages/shipjs/src/step/setup/CI/addCircleCIConfig.js, packages/shipjs/src/step/setup/CI/addGitHubActions.js, packages/shipjs/src/step/setup/addScriptsToPackageJson.js, website/guide/getting-started.md, website/guide/useful-config.md
fixes #823
only docs and some `setup` steps are modified.
=> docs: update guide on script

website/reference/all-config.md
=> docs: add "used at"

.circleci/config.yml, packages/shipjs/src/step/setup/CI/addCircleCIConfig.js, website/guide/getting-started.md, website/guide/useful-config.md
This PR adds a guide for release snapshot.
(Related to https://github.com/algolia/shipjs/pull/861)
=> chore: add guide for release snapshot

.circleci/config.yml
Fixing a mistake that was made in one of the previous PRs.
=> chore: fix circleci

.all-contributorsrc, README.md
=> feat: add contributor

.all-contributorsrc, README.md
=> docs: add @miyajan as a contributor

packages/shipjs-lib/package.json
=> chore(deps): bump `shelljs` to ensure vuln fixed

website/.vuepress/config.js
Update DocSearch credentials to match [our new infrastructure](https://docsearch.algolia.com/docs/migrating-from-legacy)
=> docs: update DocSearch credentials

.all-contributorsrc, README.md
Ref: https://github.com/algolia/shipjs/issues/968#issuecomment-1040092250
=> docs: add @vinayakkulkarni as a contributor
