- package.json
- packages/shipjs-lib/package.json
- packages/shipjs-lib/rollup.config.js
- packages/shipjs-lib/src/lib/shell/exec.js
- yarn.lock
`shelljs` used to break the build, and I've changed to require it instead of importing it.
Now it works fine. I don't understand what happens in the behind scene in the build process.
Anyway this way, it's safe to use shelljs which is more suitable than execa.
> chore: use shelljs instead of execa

- packages/shipjs-lib/src/lib/util/getNextVersion.js
> fix: skip merge commits when analysing next version

- packages/shipjs-lib/src/lib/util/__tests__/getNextVersion.spec.js
- packages/shipjs-lib/src/lib/util/getNextVersion.js
- packages/shipjs/src/step/prepare/getNextVersion.js
> fix: ignore commits out of convention instead of throwing

- CHANGELOG.md
- lerna.json
- package.json
- packages/shipjs-lib/package.json
- packages/shipjs/package.json
- packages/shipjs/src/version.js
- Version change: `v0.3.4` → `v0.4.0`
- Merge: `releases/v0.4.0` → `master`
- [Compare the changes between the versions](https://github.com/algolia/shipjs/compare/v0.3.4...releases/v0.4.0)
> chore: release v0.4.0

- packages/shipjs/src/flow/release.js
- packages/shipjs/src/step/release/createGitHubRelease.js
- packages/shipjs/src/util/wrapRun.js
This PR injects `createGitHubRelease` into `release`.
- Get changelog from `conventional-changelog`
- `hub release create` with changelog
Possibly fixes #109
> Edit PR freely
> feat: create GitHub releases

- packages/shipjs-lib/src/lib/config/defaultConfig.js
- packages/shipjs/babel.config.js
- packages/shipjs/package.json
- packages/shipjs/src/flow/release.js
- packages/shipjs/src/step/release/__tests__/createGitHubRelease.test.js
- packages/shipjs/src/step/release/__tests__/fixtures/CHANGELOG.md
- packages/shipjs/src/step/release/createGitHubRelease.js
- yarn.lock
Adding support for uploading assets to GitHub release.
Fixes #332
> feat: upload assets to GitHub release

- packages/shipjs/src/step/setup/addDevDependencies.js
`detectYarn` is function, but used as `Boolean`
Fixed that
> fix: detecting yarn in setup script

- GUIDE.md
- packages/shipjs/src/flow/prepare.js
- packages/shipjs/src/step/prepare/__tests__/printHelp.spec.js
- packages/shipjs/src/step/prepare/printHelp.js
> fix: deprecate --first-release and --release-count at shipjs prepare

- GUIDE.md
- packages/shipjs-lib/src/index.js
- packages/shipjs-lib/src/lib/config/defaultConfig.js
- packages/shipjs-lib/src/lib/util/__tests__/getReleaseType.spec.js
- packages/shipjs-lib/src/lib/util/getReleaseType.js
- packages/shipjs/src/flow/prepare.js
- packages/shipjs/src/step/prepare/__tests__/commitChanges.spec.js
- packages/shipjs/src/step/prepare/__tests__/createPullRequest.spec.js
- packages/shipjs/src/step/prepare/__tests__/updateVersion.spec.js
- packages/shipjs/src/step/prepare/__tests__/updateVersionMonorepo.spec.js
- packages/shipjs/src/step/prepare/commitChanges.js
- packages/shipjs/src/step/prepare/createPullRequest.js
- packages/shipjs/src/step/prepare/prepareStagingBranch.js
- packages/shipjs/src/step/prepare/updateVersion.js
- packages/shipjs/src/step/prepare/updateVersionMonorepo.js
Sometimes it is useful to pass release type as the release meta information to hooks.
e.g. shipjs.config.js:
```js
const releaseEmoji = {
patch: ':sparkles:',
minor: ':tada:',
major: ':confetti_ball:',
// ...
}
formatCommitMessage: ({ version, type, }) => 
`${releaseEmoji[type]}: release(${type}) v${version}`
```
I've also passed `release Type` or` type` as an argument to some hooks as release type.
> feat(releaseType): expose at hooks ("major", "minor", ...)

- packages/shipjs/src/helper/getChangelog.js
`npm run release:trigger` ends with this error:
```
› Creating a release on GitHub repository
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
at validateString (internal/validators.js:112:11)
at Proxy.resolve (path.js:981:7)
at getChangelog (/Users/jeetiss/Projects/try-shipjs/node_modules/shipjs/src/helper/getChangelog.js:7:46)
```
fix that
> fix(getChangelog): wrong argument name

- packages/shipjs/package.json
- packages/shipjs/src/flow/setup.js
- packages/shipjs/src/step/setup/addShipConfig.js
- packages/shipjs/src/step/setup/askQuestions.js
- yarn.lock
re #436 
- added question about package access on setup step
- added `isScopedPackage` verification on setup step
- added custom `publishCommand` to config, based on information from previous step
PS: I added restricted access except scoped package support, if somebody with default package (not scoped) chose don't publish public package. Setup script will add custom `publishCommand` with `--access restricted` 🤖
> feat: add support for scoped packages

- packages/shipjs/src/step/release/__tests__/runBuild.spec.js
- packages/shipjs/src/step/release/__tests__/runTest.spec.js
- packages/shipjs/src/step/release/runBuild.js
- packages/shipjs/src/step/release/runTest.js
- packages/shipjs/src/step/setup/addShipConfig.js
> fix: skip missing scripts(`test` or `build`)

- packages/shipjs/src/helper/__tests__/gitPush.spec.js
- packages/shipjs/src/helper/gitPush.js
> fix(prepare): clean up remote `origin-with-token` after git push

- GUIDE.md
Since https://github.com/algolia/shipjs/issues/437 is done, we don't need this part of documentation any more.
> docs: update guide

- packages/shipjs/src/step/setup/addShipConfig.js
> fix(setup): don't use escape for config serialization

- packages/shipjs/src/step/setup/CI/addGitHubActions.js
Github actions didn't convert secrets to env variables on default, so I added SLACK_INCOMING_HOOK secret to all shipjs commands
> fix(setup): add SLACK_INCOMING_HOOK env for all github actions

- packages/shipjs/src/step/setup/CI/addGitHubActions.js
Fix minor typo, and remove a first blank line from GitHub Actions config.
from: `runs-on: Ubuntu-latest` -> to: `runs-on: ubuntu-latest`.
> fix(github-actions): fix GitHub Action's image name

- packages/shipjs/src/step/setup/CI/addGitHubActions.js
- website/guide/getting-started.md
Just realize that we don't need `GH_TOKEN` for releases. I found library `changesets`  and they create releases with github bot 👉🏻https://github.com/atlassian/changesets/releases
I think that GITHUB_TOKEN don't provide enough rights for all todos and because of that `shipjs trigger` fails  https://github.com/jeetiss/try-shipjs/runs/330554677#step:6:54 , but problem was in different thing
I test GITHUB_TOKEN and every works fine now (see last release) https://github.com/jeetiss/try-shipjs/releases so I replace all tokens to GITHUB_TOKEN and change github actions guide
Sorry about that :)
> fix: replace GH_TOKEN with GITHUB_TOKEN

- packages/shipjs-lib/src/lib/util/__tests__/getReleaseType.spec.js
- packages/shipjs-lib/src/lib/util/getReleaseType.js
closes #594.
This PR fixes `getReleaseType`.
- `1.2.3` -> `2.0.0`: `major`
- `1.2.3` -> `1.3.0`: `minor`
- `1.2.3` -> `1.2.4`: `patch`
- `1.2.3` -> `1.2.4-alpha.0`: `prerelease`
- `1.2.4-alpha.0` -> `1.2.4-alpha.1`: `prerelease`
- `1.2.4-alpha.0` -> `1.2.4`: `patch`
- `1.2.4-alpha.0` -> `1.2.5`: `patch`
- `1.2.4-alpha.0` -> `1.3.0`: `minor`
- `1.2.4-alpha.0` -> `2.0.0`: `major`
- `1.3.0-alpha.0` -> `1.3.0`: `minor`
Just like normal cases, the new version decides the `releaseType`.
> fix: clean up all cases for releaseType

- ship.config.js
skip empty PRs, like https://github.com/algolia/shipjs/pull/656
> chore: skip preparation if master contain only `chore` commits

- packages/shipjs-lib/src/lib/util/__tests__/expandPackageList.spec.js
- packages/shipjs-lib/src/lib/util/expandPackageList.js
> fix: allow @(a|b|c) syntax for packagesToBump and packagesToPublish

- GUIDE.md
- packages/shipjs-lib/src/lib/config/defaultConfig.js
- packages/shipjs/src/step/prepare/__tests__/createPullRequest.spec.js
- packages/shipjs/src/step/prepare/createPullRequest.js
- website/guide/useful-config.md
- website/reference/all-config.md
> fix: clean up reviewer related configs

- packages/shipjs-lib/src/lib/config/defaultConfig.js
- packages/shipjs/jest.setup.js
- packages/shipjs/src/flow/prepare.js
- packages/shipjs/src/step/prepare/__tests__/getNextVersion.spec.js
- packages/shipjs/src/step/prepare/getNextVersion.js
- packages/shipjs/src/step/release/__tests__/createGitHubRelease.spec.js
- website/reference/all-config.md
> feat(prepare): add a new hook `getNextVersion`

- packages/shipjs/package.json
This is not good...
`files` key in package.json can select that not to include directory.
like this!!
https://github.com/stylelint/stylelint/blob/master/package.json#L33
> chore(shipjs): do not include __tests__ directory

- packages/shipjs-lib/src/lib/config/defaultConfig.js
- packages/shipjs/src/flow/prepare.js
- packages/shipjs/src/helper/__tests__/gitPush.spec.js
- packages/shipjs/src/helper/gitPush.js
- packages/shipjs/src/step/prepare/push.js
- packages/shipjs/src/step/release/gitPush.js
> feat: force push to protected branch with explicit config

- packages/shipjs-lib/src/lib/util/__tests__/getReleaseType.spec.js
- packages/shipjs-lib/src/lib/util/getReleaseType.js
- packages/shipjs/src/flow/prepare.js
It calculate releaseType only with nextVersion
> fix(prepare): return correct releaseType

- packages/shipjs/src/step/setup/CI/addGitHubActions.js
fix #897
improve getBaseConfig
> feat(setup): improve GitHub Actions flow made with `shipjs setup`

- packages/shipjs-lib/babel.config.js
- packages/shipjs-lib/jest.config.js
- packages/shipjs-lib/src/lib/config/__tests__/cjs/ship.config.cjs
- packages/shipjs-lib/src/lib/config/__tests__/loadConfig.spec.js
- packages/shipjs-lib/src/lib/config/loadConfig.js
- packages/shipjs-lib/src/lib/util/getAppName.js
- packages/shipjs/babel.config.js
- packages/shipjs/jest.config.js
- packages/shipjs/src/flow/prepare.js
- packages/shipjs/src/flow/release.js
- packages/shipjs/src/step/prepare/__tests__/createPullRequest.spec.js
- packages/shipjs/src/step/release/gatherRepoInfo.js
hey @eunjae-lee! 
how are you? 🙌🏻
I mirgate same of my project to esm modules with `"type": "module"`, so now i can't use shipjs, because it load only `shipjs.config.js`
I added `cjs`, `mjs`, `js` possible extensions to config and use first existed, so it should solve the problem
also improve config for tests ❤️
> feat: add basic support for esm

- packages/shipjs/src/step/setup/addShipConfig.js
This PR adds `--tag` to publishCommand in generated config by `shipjs setup`
> fix(setup): add --tag to publish command in generated config

- README.md
- packages/shipjs/src/helper/getPublishCommand.js
- packages/shipjs/src/step/release/__tests__/runPublish.spec.js
- website/guide/README.md
- website/guide/useful-config.md
- website/reference/all-config.md
This PR replaces `yarn publish` with `npm publish` even if user is using `yarn`.
`yarn publish` uses `yarn pack` under the hood, and there is [a critical bug](https://github.com/yarnpkg/yarn/issues/8332) in `yarn pack`.
Replacing `yarn publish` with `npm publish` requires an extra job, which is to set `registry` to the one of npm. Even though Ship.js calls `npm publish`, if it's triggered by `yarn shipjs trigger`, then yarn overrides the registry. It's coming from `~/.yarnrc`. To revert this back, we need to prepend `npm_config_registry=https://registry.npmjs.org/` to set the registry correctly.
> fix(trigger): replace yarn publish with npm publish

- packages/shipjs/src/helper/getPublishCommand.js
- packages/shipjs/src/step/release/__tests__/runPublish.spec.js
- packages/shipjs/src/step/release/runPublish.js
Prepending `npm_config_registry=https://registry.npmjs.org/` didn't work (https://github.com/algolia/shipjs/pull/919)
Now it just calls `yarn config set registry https://registry.npmjs.org/` to correct the registry.
> fix: update registry before publish instead of using env var which didn't work

- packages/shipjs/src/step/release/__tests__/runPublish.spec.js
- packages/shipjs/src/step/release/runPublish.js
After multiple tries, I've found that this line is needs to be inside `~/.npmrc` in order to read `NPM_AUTH_TOKEN` environment variable when `npm publish` is called.
> registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}
I feel like `npm publish` never worked before, meaning all of the Ship.js users use yarn?
> fix: set npm config to read NPM_AUTH_TOKEN

- packages/shipjs/src/step/setup/CI/addGitHubActions.js
`NODE_AUTH_TOKEN` is not used anywhere. And before fixing it, github action couldn't find `NPM_AUTH_TOKEN` from secrets so there was an issue publishing next npm package.
> fix: typo in GitHubAction config

- packages/shipjs/src/step/setup/CI/addGitHubActions.js
The GitHub Actions jobs created by `shipjs setup` use the `actions/github` action. But the `actions/github` action is deprecated and it is recommended to use the `actions/github-script` action instead.
https://github.com/actions/github
> 🚨 This action is deprecated! Please use actions/github-script, instead.
So I've fixed the generated jobs to use `actions/github-script`.
https://github.com/miyajan/test-shipjs/pull/1
I have tested the fixed `create_done_comment` and `create_fail_comment` jobs on my test repository to make sure they work correctly.
> fix: use the `actions/github-script` action instead of the deprecated `actions/github` action

- packages/shipjs/src/flow/prepare.js
- packages/shipjs/src/step/prepare/updateChangelog.js
This PR adds missing version in the changelog in case the root `package.json` has no `version` field (which is quite common in monorepos.)
It adds `version` to the conventional-changelog context explicitly, so that it won't need to read it from `package.json`.
> fix(prepare): add missing version in the changelog

- packages/shipjs-lib/src/lib/const.js
Fixes issue of `ci` type commits being flagged as out of convention when they're in the spec.
> fix: add 'ci' to list of accepted types

- website/guide/getting-started.md
The arguments of the npm script should be separated by `--`.
https://docs.npmjs.com/cli/v8/commands/npm-run-script#description
> Any positional arguments are passed to the specified script. Use -- to pass --prefixed flags and options which would otherwise be parsed by npm.
> docs: fix the argument passing in npm script

- renovate.json
This PR removes `renovate`. It's been creating a massive pull requests after every commit. We will revisit this.
> chore: remove renovate

- packages/shipjs-lib/src/lib/git/__tests__/getRemoteBranches.spec.js
- packages/shipjs-lib/src/lib/git/getRemoteBranches.js
This PR fixes `getRemoteBranches` function to get remote branches correctly when there are multiple origins.
fixes #972
> fix: get remote branches correctly when there are multiple origins

- packages/shipjs/src/step/prepare/__tests__/createPullRequest.spec.js
- packages/shipjs/src/step/prepare/createPullRequest.js
Instead of createReviewRequest, requestReviewers is used.
See: https://octokit.github.io/rest.js/v18/#pulls-request-reviewers and https://github.com/octokit/octokit.js/pull/1760
> fix(github): use non-deprecated requestReviewers function

- website/package.json
The author information in the `website` package was auto-generated. So I put Algolia instead, which seems more appropriate.
> docs: update the author info in the website package

- packages/shipjs/src/step/release/__tests__/createGitTag.spec.js
- packages/shipjs/src/step/release/createGitTag.js
Some other tools like `git describe` (used by lerna) will only return annotated tags. As well, the git documentation ([link](https://git-scm.com/book/en/v2/Git-Basics-Tagging)) primarily documents writing annotated tags.
This commit changes the behaviour of tags written by shipjs to write annotated tags
> fix(tags): write an annotated git tag

- packages/shipjs/src/step/release/__tests__/createGitHubRelease.spec.js
- packages/shipjs/src/step/release/createGitHubRelease.js
This PR allows an `extractChangelog` method set in user config to access the `tagName` property, facilitating the retrieval of an appropriate changelog in a monorepo context where publishing is left to lerna.
> feat(changelog): send tagname to changelog function

- packages/shipjs/src/step/setup/CI/addGitHubActions.js
When setting up shipjs, the user is prompted with choosing if they want to create a Github Action workflow. The template used references actions that default to Node.js 12, which is EOL and has more chance to be incompatible with some of the user's projects dependencies.
This PR updates those action to their latest version, which now default to Node.js 16.
> fix(github-actions): update versions of checkout and node actions

- packages/shipjs/src/step/release/createGitHubRelease.js
This PR enforces the asynchronous nature of the [Github Release Asset](https://docs.github.com/en/rest/releases/assets?apiVersion=2022-11-28#upload-a-release-asset) method.
**Within a CI environment**
- We ensure that assets are uploaded one after the other (as part of the release) prior to the next step in the CI (or CI termination)
> fix(github): ensure release assets are ready before releasing

- packages/shipjs/package.json
- packages/shipjs/src/step/release/__tests__/createGitHubRelease.spec.js
- packages/shipjs/src/step/release/createGitHubRelease.js
- yarn.lock
The Octokit package powering ShipJS' integration with Github changed the parameters required for uploading a release asset. This change occurred between Octokit's [v16](https://octokit.github.io/rest.js/v16#repos-upload-release-asset) and [v17](https://octokit.github.io/rest.js/v17#repos-upload-release-asset).
ShipJS currently runs on top of v17 of the Octokit package. This means that the method in charge of uploading release assets is broken.
This PR updates this method so its compatible with v17 of the Octokit package.
The PR also includes tests associated with the upload of release assets.
> fix(github): update parameters used during upload of release assets

- website/guide/getting-started.md
- There's no description about 'Nothing' configure, so I've added some description about it. Please check issue #1002 out.
> docs: update getting-started.md

- package.json
Hey team!
The Support team is currently in a process of removing support@algolia.com email from all GitHub repos and updating it to link to the new ticket form https://alg.li/support. We kindly ask that you review the changes made removing references to support@algolia.com
Thanks!
> update reference of support@aloglia.com to new ticket link
